### ISSUE TITLE
[active-active] Peer toggle issue

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-linkmgrd#143]
#### what is the issue
The flaky testcase `test_link_drop.py::test_active_link_drop_upstream` fails showing that there is a discruption for upstream traffic after simulating link drop for upstream traffic from the mux server to the upper ToR.

#### analysis

The root cause is that, once there is a link drop for upstream traffic from mux server to upper ToR, the upper ToR will receive no more heartbeats, neither from itself or its peer. The upper ToR will toggle itself, and will toggle peer if the peer heartbeat missing is detected first(the upper ToR is still healthy). In theory, those togglings should be failed since the upstream link is dropping packets.
But in fact, the toggling requests could reach the gRPC server(`nic_simulator`) and the request could be processed by `nic_simulator`. Hereby the issue, if the peer heartbeat missing is detected first, `linkmgrd` will request toggling peer, then request toggling itself, those two togglings will make both ToRs unreachable from mux server.

##### logs showing toggling peer first, then itself
* The syslog from upper ToR showing peer heartbeat missing is reported first:
```
Oct 12 10:46:10.591060 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:524 handlePeerStateChange: Ethernet8: Received peer link prober event, new state: PeerUnknown
Oct 12 10:46:10.591133 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:909 switchPeerMuxState: Ethernet8: Switching peer MUX state to 'Standby'
Oct 12 10:46:11.098198 NOTICE pmon#ycable[29]: calling RPC for hw mux_cable set state ispeer = True port Ethernet8 portid 0 read_side 1 state requested standby
Oct 12 10:46:11.590773 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:425 handleStateChange: Ethernet8: Received link prober event, new state: Unknown
Oct 12 10:46:11.590877 WARNING mux#linkmgrd: DbInterface.cpp:259 postLinkProberMetricsEvent: Ethernet8: posting link prober event link_prober_unknown_start
Oct 12 10:46:11.590933 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:881 switchMuxState: Ethernet8: Switching MUX state to 'Standby'
Oct 12 10:46:11.591185 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:445 handleStateChange: Ethernet8: (P: Active, M: Active, L: Up) -> (P: Unknown, M: Standby, L: Up)
Oct 12 10:46:11.591185 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:789 setLabel: Ethernet8: Linkmgrd state is: Standby Unhealthy
Oct 12 10:46:11.591556 WARNING mux#linkmgrd: DbInterface.cpp:511 handlePostLinkProberMetrics: Ethernet8: posting link prober event link_prober_unknown_start
Oct 12 10:46:11.593097 NOTICE swss#orchagent: :- setState: [Ethernet8] Set MUX state from active to standby
Oct 12 10:46:11.599741 NOTICE pmon#ycable[29]: response was none hw_mux_cable_table_grpc_notification Ethernet8
Oct 12 10:46:11.599880 WARNING pmon#ycable[29]: ERR: Got a change event for updating gRPC but could not toggle the mux-direction for port Ethernet8 state from unknown to standby, writing unknown
Oct 12 10:46:11.600643 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:323 handlePeerMuxStateNotification: Ethernet8: state db mux state: Unknown
Oct 12 10:46:11.603653 NOTICE swss#orchagent: :- addOperation: Mux State set to standby for port Ethernet8
Oct 12 10:46:12.105649 NOTICE pmon#ycable[29]: calling RPC for hw mux_cable set state ispeer = False port Ethernet8 portid 1 read_side 1 state requested standby
Oct 12 10:46:12.608223 NOTICE pmon#ycable[29]: response was none hw_mux_cable_table_grpc_notification Ethernet8
Oct 12 10:46:12.608644 WARNING pmon#ycable[29]: ERR: Got a change event for updating gRPC but could not toggle the mux-direction for port Ethernet8 state from active to standby, writing unknown
Oct 12 10:46:12.611272 NOTICE swss#orchagent: :- addOperation: Mux setting State DB entry (hw state unknown, mux state unknown) for port Ethernet8
Oct 12 10:46:12.611877 WARNING mux#linkmgrd: MuxManager.cpp:288 addOrUpdateMuxPortMuxState: Ethernet8: state db mux state: unknown
Oct 12 10:46:12.612204 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:170 handleMuxStateNotification: Ethernet8: state db mux state: Unknown
Oct 12 10:46:12.612246 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:463 handleStateChange: Ethernet8: Received mux state event, new state: Unknown
```

* the `nic_simulator` logs, it shows that if self heartbeats missing comes first, and only one toggle(self) will be requested:
```
2022-10-12 10:46:08,754 set_drop             INFO  #0512| Set drop on bridge baa-svc1-3-3: portids=[1], directions=[1], recover=False4
2022-10-12 10:46:08,928 query_forwarding_sta INFO  #0507| Query bridge baa-svc1-3-3 forwarding state for ports [0, 1]: ('ACTIVE', 'STANDBY')
2022-10-12 10:46:11,610 set_forwarding_state INFO  #0498| Set bridge baa-svc1-3-3 port 0 forwarding state: STANDBY
2022-10-12 10:46:11,649 query_forwarding_sta INFO  #0507| Query bridge baa-svc1-3-3 forwarding state for ports [0]: ('STANDBY',)                        // toggling peer, the lower ToR
2022-10-12 10:46:16,441 set_forwarding_state INFO  #0498| Set bridge baa-svc1-3-3 port 1 forwarding state: STANDBY
2022-10-12 10:46:16,506 query_forwarding_sta INFO  #0507| Query bridge baa-svc1-3-3 forwarding state for ports [1]: ('STANDBY',)                        // toggling itself, the upper ToR
```
##### logs shows only toggling self
* the `nic_simulator` logs that shows the toggling self is processed:
```
2022-10-12 10:46:10,110 set_drop             INFO  #0512| Set drop on bridge baa-svc1-3-5: portids=[1], directions=[1], recover=False
2022-10-12 10:46:10,329 query_forwarding_sta INFO  #0507| Query bridge baa-svc1-3-5 forwarding state for ports [0, 1]: ('ACTIVE', 'STANDBY')
2022-10-12 10:46:17,900 set_forwarding_state INFO  #0498| Set bridge baa-svc1-3-5 port 1 forwarding state: STANDBY                                      // toggling itself, the upper ToR
2022-10-12 10:46:17,961 query_forwarding_sta INFO  #0507| Query bridge baa-svc1-3-5 forwarding state for ports [1]: ('STANDBY',)
```

**Comment by lolyu** [comment]
My proposal to solve this issue is to let the ToR that tries to toggle its peer state to `standby` to send heartbeats with a special TLV to signal its peer, that there is a toggle for him. And its peer ToR should handle this special TLV receival by sending mux probes to correct its mux state, in this case, it will try to toggle itself back to `active`.

**Comment by zjswhhh** [comment]
> My proposal to solve this issue is to let the ToR that tries to toggle its peer state to `standby` to send heartbeats with a special TLV to signal its peer, that there is a toggle for him. And the peer ToR should handle this special TLV receival by sending mux probes to correct its mux state, in this case, it will try to toggle itself back to `active`.

Can peer's (lower ToR) mux probe request be served before upper ToR's toggle peer request?

**Comment by lolyu** [comment]
> > My proposal to solve this issue is to let the ToR that tries to toggle its peer state to `standby` to send heartbeats with a special TLV to signal its peer, that there is a toggle for him. And the peer ToR should handle this special TLV receival by sending mux probes to correct its mux state, in this case, it will try to toggle itself back to `active`.
> 
> Can peer's (lower ToR) mux probe request be served before upper ToR's toggle peer request?

There will be a timer to suspend the probe a little.

> 
> Maybe for peer' link prober unknown event, we take one more timeout (4 heartbeat intervals instead of 3)?

I assume 6(2 * negative retry count) is more safe here, will take this approach as it is much simpler, thanks.
