### ISSUE TITLE
flaky unit test `MuxStandbyConfigActivegRPCError`  on master branch

### ISSUE THREAD

**Issue by zjswhhh** [sonic-net/sonic-linkmgrd#218]
12:03:07  [ RUN      ] LinkManagerStateMachineActiveActiveTest.MuxStandbyConfigActivegRPCError
12:03:07  test/LinkManagerStateMachineActiveActiveTest.cpp:1004: Failure
12:03:07  Expected equality of these values:
12:03:07    std::get<0>(mTestCompositeState)
12:03:07      Which is: 2
12:03:07    link_prober::LinkProberState::Label::Wait
12:03:07      Which is: 3
12:03:07  [  FAILED  ] LinkManagerStateMachineActiveActiveTest.MuxStandbyConfigActivegRPCError (987 ms)

**Comment by baxia-lan** [comment]
Is this flakiness fixed? 

We are facing same flakiness on sonic-buildimage 202305 release branch.
